variable "gcp_project_id" {}
variable "project_id" {}
variable "gcp_credentials" {}
variable "config_name" {}
variable "gcp_zone" {}
variable "zone" {}
variable "instance_id" {}
variable "uptime_check_id" {}
variable "cluster_name" {}
variable "image_type" {}
variable "machine_type" {}
variable "node_version" {}
variable "min_master_version" {}
